name: CI
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: add permission
        run: chmod +x ./mvnw

      - name: test
        run: ./mvnw test

