name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: add permission
        run: chmod +x ./mvnw

      - name: test
        run: ./mvnw test

      - name: build project
        if: github.event_name == 'push'
        run: ./mvnw package
      - name: deploy
        if: github.event_name == 'push'
        run: ./mvnw deploy



